# Generated by Django 4.2.16 on 2025-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Available"),
                    ("sold", "Sold"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
