# Generated by Django 4.2.16 on 2025-03-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_offernotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfferNotification",
        ),
    ]
