# Generated by Django 4.2.16 on 2025-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_payment_method_refundrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("refund", "Refund"),
                    ("recharge", "Recharge"),
                ],
                default="purchase",
                max_length=20,
            ),
        ),
    ]
