# Generated by Django 4.2.16 on 2025-03-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("product_sold", "Product Sold"),
                    ("new_order", "New Order"),
                    ("order_status", "Order Status Update"),
                    ("message", "New Message"),
                    ("review", "New Review"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_approved", "Refund Approved"),
                    ("refund_rejected", "Refund Rejected"),
                    ("refund_completed", "Refund Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
